apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki-uid
    url: http://loki:3100
    access: proxy
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: severity
          matcherRegex: '"sev":\s?"(\w+)"'
          url: ''
        - name: pred
          matcherRegex: '"pred":\s?"(\w+)"'
          url: ''
