server:
  http_listen_port: 3100
  log_level: info

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fhir-alerts
    static_configs:
      - targets:
          - localhost
        labels:
          job: fhir-security
          service: edge-fhir-hybrid
          __path__: /logs/alerts.log

  - job_name: fhir-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: fhir-server
          service: edge-fhir-hybrid
          __path__: /logs/server.log
